%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)
% Modified by Brent Bundick for impulse response matching
% Note: % % Denote deletions or modifications

% % clear all
% % tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'bbeffectivedemandmatchirf';
%
% Some global variables initialization
%
global_initialization;
% % diary off;
% % diary('bbeffectivedemandmatchirf.log');
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names_long = 'ea';
M_.exo_names = char(M_.exo_names, 'evola');
M_.exo_names_tex = char(M_.exo_names_tex, 'evola');
M_.exo_names_long = char(M_.exo_names_long, 'evola');
M_.exo_names = char(M_.exo_names, 'ez');
M_.exo_names_tex = char(M_.exo_names_tex, 'ez');
M_.exo_names_long = char(M_.exo_names_long, 'ez');
M_.endo_names = 'a';
M_.endo_names_tex = 'a';
M_.endo_names_long = 'a';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'de');
M_.endo_names_tex = char(M_.endo_names_tex, 'de');
M_.endo_names_long = char(M_.endo_names_long, 'de');
M_.endo_names = char(M_.endo_names, 'deltau');
M_.endo_names_tex = char(M_.endo_names_tex, 'deltau');
M_.endo_names_long = char(M_.endo_names_long, 'deltau');
M_.endo_names = char(M_.endo_names, 'deltauprime');
M_.endo_names_tex = char(M_.endo_names_tex, 'deltauprime');
M_.endo_names_long = char(M_.endo_names_long, 'deltauprime');
M_.endo_names = char(M_.endo_names, 'expre');
M_.endo_names_tex = char(M_.endo_names_tex, 'expre');
M_.endo_names_long = char(M_.endo_names_long, 'expre');
M_.endo_names = char(M_.endo_names, 'expre2');
M_.endo_names_tex = char(M_.endo_names_tex, 'expre2');
M_.endo_names_long = char(M_.endo_names_long, 'expre2');
M_.endo_names = char(M_.endo_names, 'expvf1sigma');
M_.endo_names_tex = char(M_.endo_names_tex, 'expvf1sigma');
M_.endo_names_long = char(M_.endo_names_long, 'expvf1sigma');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'pe');
M_.endo_names_tex = char(M_.endo_names_tex, 'pe');
M_.endo_names_long = char(M_.endo_names_long, 'pe');
M_.endo_names = char(M_.endo_names, 'pie');
M_.endo_names_tex = char(M_.endo_names_tex, 'pie');
M_.endo_names_long = char(M_.endo_names_long, 'pie');
M_.endo_names = char(M_.endo_names, 'profit');
M_.endo_names_tex = char(M_.endo_names_tex, 'profit');
M_.endo_names_long = char(M_.endo_names_long, 'profit');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'rr');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr');
M_.endo_names_long = char(M_.endo_names_long, 'rr');
M_.endo_names = char(M_.endo_names, 'rrk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrk');
M_.endo_names_long = char(M_.endo_names_long, 'rrk');
M_.endo_names = char(M_.endo_names, 'sdf');
M_.endo_names_tex = char(M_.endo_names_tex, 'sdf');
M_.endo_names_long = char(M_.endo_names_long, 'sdf');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'varexpre');
M_.endo_names_tex = char(M_.endo_names_tex, 'varexpre');
M_.endo_names_long = char(M_.endo_names_long, 'varexpre');
M_.endo_names = char(M_.endo_names, 'vf');
M_.endo_names_tex = char(M_.endo_names_tex, 'vf');
M_.endo_names_long = char(M_.endo_names_long, 'vf');
M_.endo_names = char(M_.endo_names, 'vola');
M_.endo_names_tex = char(M_.endo_names_tex, 'vola');
M_.endo_names_long = char(M_.endo_names_long, 'vola');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.param_names = 'alpha';
M_.param_names_tex = 'alpha';
M_.param_names_long = 'alpha';
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'delta0');
M_.param_names_tex = char(M_.param_names_tex, 'delta0');
M_.param_names_long = char(M_.param_names_long, 'delta0');
M_.param_names = char(M_.param_names, 'delta1');
M_.param_names_tex = char(M_.param_names_tex, 'delta1');
M_.param_names_long = char(M_.param_names_long, 'delta1');
M_.param_names = char(M_.param_names, 'delta2');
M_.param_names_tex = char(M_.param_names_tex, 'delta2');
M_.param_names_long = char(M_.param_names_long, 'delta2');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'phip');
M_.param_names_tex = char(M_.param_names_tex, 'phip');
M_.param_names_long = char(M_.param_names_long, 'phip');
M_.param_names = char(M_.param_names, 'phik');
M_.param_names_tex = char(M_.param_names_tex, 'phik');
M_.param_names_long = char(M_.param_names_long, 'phik');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'ies');
M_.param_names_tex = char(M_.param_names_tex, 'ies');
M_.param_names_long = char(M_.param_names_long, 'ies');
M_.param_names = char(M_.param_names, 'frischlse');
M_.param_names_tex = char(M_.param_names_tex, 'frischlse');
M_.param_names_long = char(M_.param_names_long, 'frischlse');
M_.param_names = char(M_.param_names, 'thetavf');
M_.param_names_tex = char(M_.param_names_tex, 'thetavf');
M_.param_names_long = char(M_.param_names_long, 'thetavf');
M_.param_names = char(M_.param_names, 'thetamu');
M_.param_names_tex = char(M_.param_names_tex, 'thetamu');
M_.param_names_long = char(M_.param_names_long, 'thetamu');
M_.param_names = char(M_.param_names, 'leverageratio');
M_.param_names_tex = char(M_.param_names_tex, 'leverageratio');
M_.param_names_long = char(M_.param_names_long, 'leverageratio');
M_.param_names = char(M_.param_names, 'fixedcost');
M_.param_names_tex = char(M_.param_names_tex, 'fixedcost');
M_.param_names_long = char(M_.param_names_long, 'fixedcost');
M_.param_names = char(M_.param_names, 'rhor');
M_.param_names_tex = char(M_.param_names_tex, 'rhor');
M_.param_names_long = char(M_.param_names_long, 'rhor');
M_.param_names = char(M_.param_names, 'rhopie');
M_.param_names_tex = char(M_.param_names_tex, 'rhopie');
M_.param_names_long = char(M_.param_names_long, 'rhopie');
M_.param_names = char(M_.param_names, 'rhoy');
M_.param_names_tex = char(M_.param_names_tex, 'rhoy');
M_.param_names_long = char(M_.param_names_long, 'rhoy');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhovola');
M_.param_names_tex = char(M_.param_names_tex, 'rhovola');
M_.param_names_long = char(M_.param_names_long, 'rhovola');
M_.param_names = char(M_.param_names, 'volvola');
M_.param_names_tex = char(M_.param_names_tex, 'volvola');
M_.param_names_long = char(M_.param_names_long, 'volvola');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'productionconstant');
M_.param_names_tex = char(M_.param_names_tex, 'productionconstant');
M_.param_names_long = char(M_.param_names_long, 'productionconstant');
M_.param_names = char(M_.param_names, 'utilityconstant');
M_.param_names_tex = char(M_.param_names_tex, 'utilityconstant');
M_.param_names_long = char(M_.param_names_long, 'utilityconstant');
M_.param_names = char(M_.param_names, 'ass');
M_.param_names_tex = char(M_.param_names_tex, 'ass');
M_.param_names_long = char(M_.param_names_long, 'ass');
M_.param_names = char(M_.param_names, 'css');
M_.param_names_tex = char(M_.param_names_tex, 'css');
M_.param_names_long = char(M_.param_names_long, 'css');
M_.param_names = char(M_.param_names, 'dess');
M_.param_names_tex = char(M_.param_names_tex, 'dess');
M_.param_names_long = char(M_.param_names_long, 'dess');
M_.param_names = char(M_.param_names, 'deltauss');
M_.param_names_tex = char(M_.param_names_tex, 'deltauss');
M_.param_names_long = char(M_.param_names_long, 'deltauss');
M_.param_names = char(M_.param_names, 'deltauprimess');
M_.param_names_tex = char(M_.param_names_tex, 'deltauprimess');
M_.param_names_long = char(M_.param_names_long, 'deltauprimess');
M_.param_names = char(M_.param_names, 'express');
M_.param_names_tex = char(M_.param_names_tex, 'express');
M_.param_names_long = char(M_.param_names_long, 'express');
M_.param_names = char(M_.param_names, 'expre2ss');
M_.param_names_tex = char(M_.param_names_tex, 'expre2ss');
M_.param_names_long = char(M_.param_names_long, 'expre2ss');
M_.param_names = char(M_.param_names, 'expvf1sigmass');
M_.param_names_tex = char(M_.param_names_tex, 'expvf1sigmass');
M_.param_names_long = char(M_.param_names_long, 'expvf1sigmass');
M_.param_names = char(M_.param_names, 'invss');
M_.param_names_tex = char(M_.param_names_tex, 'invss');
M_.param_names_long = char(M_.param_names_long, 'invss');
M_.param_names = char(M_.param_names, 'kss');
M_.param_names_tex = char(M_.param_names_tex, 'kss');
M_.param_names_long = char(M_.param_names_long, 'kss');
M_.param_names = char(M_.param_names, 'nss');
M_.param_names_tex = char(M_.param_names_tex, 'nss');
M_.param_names_long = char(M_.param_names_long, 'nss');
M_.param_names = char(M_.param_names, 'muss');
M_.param_names_tex = char(M_.param_names_tex, 'muss');
M_.param_names_long = char(M_.param_names_long, 'muss');
M_.param_names = char(M_.param_names, 'pess');
M_.param_names_tex = char(M_.param_names_tex, 'pess');
M_.param_names_long = char(M_.param_names_long, 'pess');
M_.param_names = char(M_.param_names, 'piess');
M_.param_names_tex = char(M_.param_names_tex, 'piess');
M_.param_names_long = char(M_.param_names_long, 'piess');
M_.param_names = char(M_.param_names, 'profitss');
M_.param_names_tex = char(M_.param_names_tex, 'profitss');
M_.param_names_long = char(M_.param_names_long, 'profitss');
M_.param_names = char(M_.param_names, 'qss');
M_.param_names_tex = char(M_.param_names_tex, 'qss');
M_.param_names_long = char(M_.param_names_long, 'qss');
M_.param_names = char(M_.param_names, 'rss');
M_.param_names_tex = char(M_.param_names_tex, 'rss');
M_.param_names_long = char(M_.param_names_long, 'rss');
M_.param_names = char(M_.param_names, 'rrss');
M_.param_names_tex = char(M_.param_names_tex, 'rrss');
M_.param_names_long = char(M_.param_names_long, 'rrss');
M_.param_names = char(M_.param_names, 'rrkss');
M_.param_names_tex = char(M_.param_names_tex, 'rrkss');
M_.param_names_long = char(M_.param_names_long, 'rrkss');
M_.param_names = char(M_.param_names, 'sdfss');
M_.param_names_tex = char(M_.param_names_tex, 'sdfss');
M_.param_names_long = char(M_.param_names_long, 'sdfss');
M_.param_names = char(M_.param_names, 'uss');
M_.param_names_tex = char(M_.param_names_tex, 'uss');
M_.param_names_long = char(M_.param_names_long, 'uss');
M_.param_names = char(M_.param_names, 'varexpress');
M_.param_names_tex = char(M_.param_names_tex, 'varexpress');
M_.param_names_long = char(M_.param_names_long, 'varexpress');
M_.param_names = char(M_.param_names, 'vfss');
M_.param_names_tex = char(M_.param_names_tex, 'vfss');
M_.param_names_long = char(M_.param_names_long, 'vfss');
M_.param_names = char(M_.param_names, 'volass');
M_.param_names_tex = char(M_.param_names_tex, 'volass');
M_.param_names_long = char(M_.param_names_long, 'volass');
M_.param_names = char(M_.param_names, 'volzss');
M_.param_names_tex = char(M_.param_names_tex, 'volzss');
M_.param_names_long = char(M_.param_names_long, 'volzss');
M_.param_names = char(M_.param_names, 'wss');
M_.param_names_tex = char(M_.param_names_tex, 'wss');
M_.param_names_long = char(M_.param_names_long, 'wss');
M_.param_names = char(M_.param_names, 'yss');
M_.param_names_tex = char(M_.param_names_tex, 'yss');
M_.param_names_long = char(M_.param_names_long, 'yss');
M_.param_names = char(M_.param_names, 'zss');
M_.param_names_tex = char(M_.param_names_tex, 'zss');
M_.param_names_long = char(M_.param_names_long, 'zss');
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 27;
M_.param_nbr = 52;
M_.orig_endo_nbr = 27;
M_.aux_vars = [];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('bbeffectivedemandmatchirf_static');
erase_compiled_function('bbeffectivedemandmatchirf_dynamic');
M_.lead_lag_incidence = [
 1 10 0;
 2 11 0;
 0 12 37;
 0 13 38;
 0 14 0;
 0 15 0;
 0 16 0;
 3 17 0;
 0 18 39;
 4 19 0;
 0 20 0;
 5 21 0;
 0 22 40;
 0 23 41;
 0 24 0;
 0 25 42;
 6 26 0;
 0 27 0;
 0 28 43;
 0 29 44;
 0 30 45;
 0 31 0;
 0 32 46;
 7 33 0;
 0 34 0;
 8 35 47;
 9 36 0;]';
M_.nstatic = 8;
M_.nfwrd   = 10;
M_.npred   = 8;
M_.nboth   = 1;
M_.nsfwrd   = 11;
M_.nspred   = 9;
M_.ndynamic   = 19;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(27, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(52, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 118;
M_.NNZDerivatives(2) = 253;
M_.NNZDerivatives(3) = 953;
% % sigmaestimate 			= 60;
% % phikestimate			= 2;
% % rhovolaestimate 		= 0.7622;
% % volvolaestimate			= 0.0029;
M_.params( 1 ) = 0.333;
alpha = M_.params( 1 );
M_.params( 2 ) = 0.994;
beta = M_.params( 2 );
M_.params( 3 ) = 0.025;
delta0 = M_.params( 3 );
M_.params( 4 ) = 1/M_.params(2)-1+M_.params(3);
delta1 = M_.params( 4 );
M_.params( 5 ) = 0.00031;
delta2 = M_.params( 5 );
M_.params( 7 ) = 100;
phip = M_.params( 7 );
M_.params( 8 ) = phikestimate;
phik = M_.params( 8 );
M_.params( 9 ) = 80;
sigma = M_.params( 9 );
M_.params( 10 ) = 0.95;
ies = M_.params( 10 );
M_.params( 11 ) = 2.0;
frischlse = M_.params( 11 );
M_.params( 12 ) = (1-M_.params(9))/(1-1/M_.params(10));
thetavf = M_.params( 12 );
M_.params( 13 ) = 6.0;
thetamu = M_.params( 13 );
M_.params( 14 ) = 0.90;
leverageratio = M_.params( 14 );
M_.params( 38 ) = 1.005;
piess = M_.params( 38 );
M_.params( 41 ) = M_.params(38)/M_.params(2);
rss = M_.params( 41 );
M_.params( 16 ) = 0.000;
rhor = M_.params( 16 );
M_.params( 17 ) = 1.5;
rhopie = M_.params( 17 );
M_.params( 18 ) = 0.2;
rhoy = M_.params( 18 );
M_.params( 25 ) = 1;
ass = M_.params( 25 );
M_.params( 19 ) = rhoaestimate;
rhoa = M_.params( 19 );
M_.params( 48 ) = volassestimate;
volass = M_.params( 48 );
M_.params( 20 ) = rhovolaestimate;
rhovola = M_.params( 20 );
M_.params( 21 ) = volvolaestimate;
volvola = M_.params( 21 );
M_.params( 52 ) = 1;
zss = M_.params( 52 );
M_.params( 22 ) = rhozestimate;
rhoz = M_.params( 22 );
M_.params( 49 ) = volzssestimate;
volzss = M_.params( 49 );
M_.params( 51 ) = 1.0;
yss = M_.params( 51 );
M_.params( 43 ) = 1/M_.params(2)-1+M_.params(3);
rrkss = M_.params( 43 );
M_.params( 36 ) = M_.params(13)/(M_.params(13)-1);
muss = M_.params( 36 );
M_.params( 45 ) = 1;
uss = M_.params( 45 );
M_.params( 15 ) = (M_.params(36)-1)*M_.params(51);
fixedcost = M_.params( 15 );
M_.params( 34 ) = M_.params(1)*(M_.params(51)+M_.params(15))/(M_.params(36)*M_.params(43));
kss = M_.params( 34 );
M_.params( 33 ) = M_.params(3)*M_.params(34);
invss = M_.params( 33 );
M_.params( 26 ) = M_.params(51)-M_.params(33);
css = M_.params( 26 );
nsssolution = fsolve(@(nssguess) 1+(-1+1/ies)/(1+((-1+alpha)*(-1+nssguess)*(fixedcost+yss))/(css*nssguess*muss)) -(frischlse/ies)*nssguess*(1-nssguess)^(-1),0.5,optimoptions('fsolve','Display','off'));
M_.params( 35 ) = nsssolution;
nss = M_.params( 35 );
M_.params( 50 ) = (M_.params(51)+M_.params(15))*(1-M_.params(1))/(M_.params(36)*M_.params(35));
wss = M_.params( 50 );
M_.params( 6 ) = (1+M_.params(50)*(1-M_.params(35))/M_.params(26))^(-1);
eta = M_.params( 6 );
M_.params( 40 ) = 1;
qss = M_.params( 40 );
M_.params( 23 ) = (M_.params(51)+M_.params(15))/(M_.params(34)^M_.params(1)*M_.params(35)^(1-M_.params(1)));
productionconstant = M_.params( 23 );
M_.params( 47 ) = 1;
vfss = M_.params( 47 );
M_.params( 24 ) = M_.params(47)^((1-M_.params(9))/M_.params(12))*(1-M_.params(2))/(M_.params(26)^M_.params(6)*(1-M_.params(35))^(1-M_.params(6)))^((1-M_.params(9))/M_.params(12));
utilityconstant = M_.params( 24 );
M_.params( 27 ) = M_.params(26)-M_.params(35)*M_.params(50)+M_.params(34)*M_.params(14)*(M_.params(2)-1);
dess = M_.params( 27 );
M_.params( 37 ) = M_.params(2)*(1-M_.params(2))^(-1)*M_.params(27);
pess = M_.params( 37 );
M_.params( 39 ) = (M_.params(36)-1)*M_.params(51)-M_.params(15);
profitss = M_.params( 39 );
M_.params( 30 ) = 1/M_.params(2);
express = M_.params( 30 );
M_.params( 31 ) = 1/M_.params(2)^2;
expre2ss = M_.params( 31 );
M_.params( 46 ) = 0;
varexpress = M_.params( 46 );
M_.params( 32 ) = M_.params(47)^(1-M_.params(9));
expvf1sigmass = M_.params( 32 );
M_.params( 40 ) = 1;
qss = M_.params( 40 );
M_.params( 42 ) = 1/M_.params(2);
rrss = M_.params( 42 );
M_.params( 44 ) = M_.params(2);
sdfss = M_.params( 44 );
M_.params( 28 ) = M_.params(3);
deltauss = M_.params( 28 );
M_.params( 29 ) = M_.params(4);
deltauprimess = M_.params( 29 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = M_.params(25);
oo_.steady_state( 2 ) = M_.params(26);
oo_.steady_state( 3 ) = M_.params(27);
oo_.steady_state( 4 ) = M_.params(3);
oo_.steady_state( 5 ) = M_.params(4);
oo_.steady_state( 6 ) = M_.params(30);
oo_.steady_state( 7 ) = M_.params(31);
oo_.steady_state( 8 ) = M_.params(32);
oo_.steady_state( 9 ) = M_.params(33);
oo_.steady_state( 10 ) = M_.params(34);
oo_.steady_state( 12 ) = M_.params(35);
oo_.steady_state( 11 ) = M_.params(36);
oo_.steady_state( 13 ) = M_.params(37);
oo_.steady_state( 14 ) = M_.params(38);
oo_.steady_state( 15 ) = M_.params(39);
oo_.steady_state( 16 ) = M_.params(40);
oo_.steady_state( 17 ) = M_.params(41);
oo_.steady_state( 18 ) = M_.params(42);
oo_.steady_state( 19 ) = M_.params(43);
oo_.steady_state( 20 ) = M_.params(44);
oo_.steady_state( 21 ) = M_.params(45);
oo_.steady_state( 22 ) = M_.params(46);
oo_.steady_state( 23 ) = M_.params(47);
oo_.steady_state( 24 ) = M_.params(48);
oo_.steady_state( 25 ) = M_.params(50);
oo_.steady_state( 26 ) = M_.params(51);
oo_.steady_state( 27 ) = M_.params(52);
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
steadynoprint;
[oo_.dr.eigval,checkresult] = checknoprint(M_,options_,oo_);

if checkresult ~=0 
    %
    % SHOCKS instructions
    %
    make_ex_;
    M_.exo_det_length = 0;
    M_.Sigma_e(1, 1) = 1;
    M_.Sigma_e(2, 2) = 1;
    M_.Sigma_e(3, 3) = 1;
    options_.irf = 0;
    options_.nocorr = 1;
    options_.nofunctions = 1;
    options_.nograph = 1;
    options_.nomoments = 1;
    options_.noprint = 1;
    options_.order = 3;
    options_.periods = 0;
    options_.pruning = 1;
    var_list_=[];
    info = stoch_simul(var_list_);

    computeirfsmoments
        
    
end
% save('bbeffectivedemandmatchirf_results.mat', 'oo_', 'M_', 'options_');
% if exist('estim_params_', 'var') == 1
%   save('bbeffectivedemandmatchirf_results.mat', 'estim_params_', '-append');
% end
% if exist('bayestopt_', 'var') == 1
%   save('bbeffectivedemandmatchirf_results.mat', 'bayestopt_', '-append');
% end
% if exist('dataset_', 'var') == 1
%   save('bbeffectivedemandmatchirf_results.mat', 'dataset_', '-append');
% end
% if exist('estimation_info', 'var') == 1
%   save('bbeffectivedemandmatchirf_results.mat', 'estimation_info', '-append');
% end
% 
% 
% disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
% diary off
